kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim 
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 8Gi 
  storageClassName: ocs-storagecluster-cephfs